"""fix review datetime

Revision ID: fb2da30b2764
Revises: bfff3c7f94bb
Create Date: 2026-06-20 16:36:00.834391
"""
from alembic import op
import sqlalchemy as sa


revision = 'fb2da30b2764'
down_revision = 'bfff3c7f94bb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute('ALTER TABLE reviews ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE USING created_at::timestamp with time zone')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reviews', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###